name: Release 

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Release Version(next, beta, alpha, latest)'
        required: true
        default: 'next'
        options:
          - next
          - beta
          - alpha
          - latest
      branch:
        description: 'Release Branch(confirm release branch)'
        required: true
        default: 'main'

jobs:
  create:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: test workflow
        run: |
            sleep 10;
            echo 'success';
                   
